[versions]

minSdkVersion = "23"
targetSdkVersion = "36"
compileSdkVersion = "36"

agp = "8.13.0"
sonarqube = "7.0.1.6134"

appcompat = "1.7.1"
camerax = "1.5.1"
constraintlayout = "2.2.1"
exifinterface = "1.4.1"
glide = "5.0.5"

junit = "4.13.2"
material = "1.13.0"



[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
sonar-qube = { id = "org.sonarqube", version.ref = "sonarqube" }
maven-publish = { id = "maven-publish"}




